version: '3.7'

services:
  transactions:
    build: .
    env_file:
      - .env
    environment:
     - ENV=prod
     - GIN_MODE=release
     - DEBUG=false
    ports:
      - 3000:3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    volumes:
      - root-db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  root-db-data:
