
version: '3'

services:
  transactions:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: tail -f /dev/null
    ports:
      - 3000:3000
    volumes:
      - ..:/src/user-transactions
  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
