
version: '3'

services:
  transactions:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports:
      - 3000:3000
    volumes:
      - ..:/src/user-transactions

